import { createAction } from 'redux-actions';

export const GET_NATIONAL = 'GET_NATIONAL';
export const SET_NATIONAL = 'SET_NATIONAL';
export const GET_CALLING_CODE = 'GET_CALLING_CODE';
export const SET_CALLING_CODE = 'SET_CALLING_CODE';
export const SET_CANDIDATES = 'SET_CANDIDATES';
export const GET_CANDIDATES = 'GET_CANDIDATES';
export const SET_CANDIDATES_REDUX_STORE = 'SET_CANDIDATES_REDUX_STORE';
export const SET_CANDIDATES_FORM = 'SET_CANDIDATES_FORM';
export const RESET_CANDIDATE_FORM = 'RESET_CANDIDATE_FORM';
export const DELETE_CANDIDATES = 'DELETE_CANDIDATES';
export const DELETE_ALL_CANDIDATES = 'DELETE_ALL_CANDIDATES';
export const PULL_OUT_CANDIDATES = 'PULL_OUT_CANDIDATES';
export const SELECT_EDIT_CANDIDATE = 'SELECT_EDIT_CANDIDATE';
export const SET_NEW_FORM = 'SET_NEW_FORM';

export const getNanional = createAction(GET_NATIONAL);
export const setNanional = createAction(SET_NATIONAL);
export const getCallingCode = createAction(GET_CALLING_CODE);
export const setCallingCode = createAction(SET_CALLING_CODE);
export const setCandidates = createAction(SET_CANDIDATES);
export const getCandidates = createAction(GET_CANDIDATES);
export const setCandidatesReduxStore = createAction(SET_CANDIDATES_REDUX_STORE);
export const setCandidatesForm = createAction(SET_CANDIDATES_FORM);
export const resetCandidateForm = createAction(RESET_CANDIDATE_FORM);
export const deleteCandidates = createAction(DELETE_CANDIDATES);
export const deleteAllCandidates = createAction(DELETE_ALL_CANDIDATES);
export const pullOutCandidates = createAction(PULL_OUT_CANDIDATES);
export const selectEditCandidate = createAction(SELECT_EDIT_CANDIDATE);
export const setNewForm = createAction(SET_NEW_FORM);
